apiVersion: v1
kind: Pod
metadata:
  name: datasimulatordemo
spec:
  nodeName: ip-172-31-11-89
  hostNetwork: true
  containers:
    - name: datasimulatordemo
      image: 783584839454.dkr.ecr.ap-south-1.amazonaws.com/autodatasimulatordemo:latest
      imagePullPolicy: Always
      env:
       - name: CAN_IF
         value: "vcan0"
      ports:
       - name: http
         containerPort: 3000
         protocol: TCP
  imagePullSecrets:
    - name: regcred
